In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [25]:
df.head()

          Pais Pais  años  Esperanza de vida
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [ ]:
#Renombrar columnas
df.rename(columns={"entity": "Pais"}, inplace=True)
df.rename(columns={"code": "codigo"}, inplace=True)
df.rename(columns={"year": "años"}, inplace=True)
df.rename(columns={"life_expectancy_0": "Esperanza de vida"}, inplace=True)

In [33]:
df.head()

          Pais codigo  años  Esperanza de vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138
3  Afghanistan    AFG  1953            29.4521
4  Afghanistan    AFG  1954            29.6975

In [32]:
df.set_index("Pais")

            codigo  años  Esperanza de vida
Pais
Afghanistan    AFG  1950            28.1563
Afghanistan    AFG  1951            28.5836
Afghanistan    AFG  1952            29.0138
Afghanistan    AFG  1953            29.4521
Afghanistan    AFG  1954            29.6975
...            ...   ...                ...
Zimbabwe       ZWE  2019            61.0603
Zimbabwe       ZWE  2020            61.5300
Zimbabwe       ZWE  2021            60.1347
Zimbabwe       ZWE  2022            62.3601
Zimbabwe       ZWE  2023            62.7748

[21565 rows x 3 columns]

In [31]:
print(df.columns.tolist())

['Pais', 'codigo', 'años', 'Esperanza de vida']

In [30]:
df.columns = [
    "Pais",
    "codigo",
    "años",
    "Esperanza de vida"
]

In [34]:
df.loc[df["Pais"].str.contains("U", case = False, regex = True)]

                    Pais codigo  años  Esperanza de vida
604             Anguilla    AIA  1950            55.0563
605             Anguilla    AIA  1951            55.5932
606             Anguilla    AIA  1952            56.0813
607             Anguilla    AIA  1953            56.5817
608             Anguilla    AIA  1954            57.0804
...                  ...    ...   ...                ...
21183  Wallis and Futuna    WLF  2019            77.9936
21184  Wallis and Futuna    WLF  2020            78.1637
21185  Wallis and Futuna    WLF  2021            77.4609
21186  Wallis and Futuna    WLF  2022            78.5005
21187  Wallis and Futuna    WLF  2023            78.6286

[7375 rows x 4 columns]

In [37]:
df.dropna(subset=["codigo"], inplace=True)
df.isnull().sum()

Pais                 0
codigo               0
años                 0
Esperanza de vida    0
dtype: int64

In [42]:
resultado = (
    df.groupby("Pais")["Esperanza de vida"]
      .mean()
      .sort_values(ascending=True)
)
print(resultado)

Pais
USSR             32.700000
South Sudan      37.841631
Sierra Leone     43.189605
Mali             43.760793
Niger            44.187513
                   ...
Liechtenstein    76.288354
Guernsey         76.995827
Andorra          77.991046
San Marino       77.997265
Monaco           78.048231
Name: Esperanza de vida, Length: 247, dtype: float64

In [43]:
df[df["años"] == 2020].nsmallest(1, "Esperanza de vida")[["Pais", "Esperanza de vida"]]

                          Pais  Esperanza de vida
3423  Central African Republic            50.5959